[data_sources]

## Subscription data sets. Subscription needed, api key needed.
# Set to true if subscription is available, data will be pulled from source
wrds_bank_premium = true
wrds_compustat = false
wrds_corp_bonds = true
wrds_crsp_compustat = true
wrds_markit = true
wrds_optionmetrics = false

## Public data sets. No subscription needed, no api key needed.
# Default to true to download the data
fed_yield_curve = true
ken_french_data_library = true
nyu_call_report = true

[models]
# Traditional Time Series Models
var = true  # Vector Autoregression
vecm = true  # Vector Error Correction Model

# Deep Learning Models
lstm = true  # Long Short-Term Memory
transformer = true  # Transformer Architecture
temporal_fusion = false  # Temporal Fusion Transformer
neural_prophet = false  # Neural Prophet

# Hybrid Models
deep_ar = false  # Deep AutoRegressive
deep_state = false  # Deep State Space
deep_factors = false  # Deep Factor Model

# Ensemble Methods
random_forest_ts = true  # Random Forest for Time Series
xgboost_ts = true  # XGBoost for Time Series
lightgbm_ts = false  # LightGBM for Time Series
